/*
 * This file was generated by the Gradle 'init' task.
 *
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.2.2/userguide/multi_project_builds.html
 */

rootProject.name = "ktcheck-root"
include("ktcheck")
include("ktcheck-api")
include("ktcheck-engine")
include("ktcheck-example")
include("ktcheck-assertion")
include("ktcheck-document")
