/*
 * This file was generated by the Gradle 'init' task.
 *
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.2.2/userguide/multi_project_builds.html
 */

rootProject.name = "ko-check-root"
include("ko-check")
include("ko-check-api")
include("ko-check-engine")
include("ko-check-example")
include("ko-check-assertion")
