[user-program] as user

[ktcheck] as kc
[ktcheck-api] as api
[ktcheck-assertion] as ast
[ktcheck-engine] as eng
[junit-platform-engine] as jen
[opentest4j] as open

user --> kc : implementation

kc -> ast : api
kc --> api : api
kc --> eng : implementation

ast --> api : implementation

api --> open : implementation

eng -> api : implementation
eng --> jen : implementation
eng --> open : implementation
